openapi: 3.0.0
info:
  description: "{{ .Config.Description }}"
  version: "{{ .Config.Version }}"
  title: "{{ .Config.Title }}"
servers:
  - url: "{{ .Config.BasePath }}"
tags:
{{ range $key, $value := .Entities }}
- name: "{{ $key | GetGroupName }}"
  description: ""
{{ end }}
paths:
{{- range $key, $paths := .Entities }}
{{- range $path, $resources := $paths }}
  {{ $path | RemovePathPrefix}}:
    {{- range $kk, $resource := $resources }}
    {{ $resource.Method | ToLower }}:
      tags:
      - "{{ $key | GetGroupName }}"
      summary: "{{ $resource.Name }}"
      {{- if or $resource.Parameters $resource.Body.Params $resource.Headers }}
      {{- if $resource.Body.MimeType }}
      description: "{{ $resource.Description }}"
      {{- end }}
      parameters:
      {{- range $p, $param := $resource.Parameters}}
      - name: "{{ $param.Name }}"
        in: "query"
        schema:
          type: "string"
        description: ""
        required: true
      {{- end }}
      {{- range $p, $param := $resource.Headers}}
      {{if $param.IsAllowed }}
      - name: "{{ $param.Name }}"
        in: "header"
        schema:
          type: "string"
        description: ""
        required: true
      {{- end }}
      {{- end }}
      {{- end }}
      responses:
        200:
          description: "successful operation"
    {{- end }}
{{- end }}
{{- end }}
